### PR TITLE
Expand tut5.ne into a fully commented tutorial

### PR DESCRIPTION
**Pull request by emmawinston**
Commented tut5.ne and updated syntax of code examples in line with the documentation for Sema. 

The one point of uncertainty here is I'm unsure whether the 'mix' function _is_ actually affecting the amplitude/level of the nested signal processors rather than any other parameter contained within them - 'mean of all parameters' as documented [here](https://github.com/emmawinston/eppEditor/blob/master/doc/semaIR.md) does not (explicitly at least) seem to account for parameters like sigp which aren't purely numerical. Please edit or reject the PR if I've got this wrong!

### CODE REVIEW

**Comment by sensestage** [comment]
in `mix` the mean is quite basic - it is just calculating the sum and dividing by the amount of elements in the mix (so mix( sig1, sig2, sig3 ) is the same as sum( sig1, sig2, sig3 ) / 3.

**Comment by emmawinston** [comment]
Thank you! Maybe I haven't articulated my confusion properly - I'm not sure what property of the signal is being summed.

**Comment by sensestage** [comment]
the output of it signal generator. Each signal produces a floating point value calculated at each audio sample. So sum adds these values from each signal at each audio sample, and mix then also divides that result again by the amount of signals. For continuous signals this means that the volume stays roughly the same, for less continuous sounds (like beats) that means that the sound is softer (that's why you saw during the performances people used sum instead of mix for mixing together kicks, snares and hats).

**Comment by emmawinston** [comment]
Right, so we are talking amplitude - that makes sense, thank you! 

(For what it's worth, the information about the value produced by the signal is the kind of detail I would love to see in the SemaIR reference docs, but that may not be a universal view! :) )

**Pull request closed without merging**
